### ISSUE TITLE
next url 

### ISSUE THREAD

**Issue by vptcnt** [Illniyar/visor#5]
Hello

The next parameter is always filled with the url where I came from, and not the restricted url ?

I am using the ui-router version.

any idea ?

**Comment by Illniyar** [comment]
are you using 0.0.4 ? there was a slight issue with the next param in 0.0.3 with angular 1.3.x (look at bower.json if you are using browserify, the version text in the actual file wasn't properly updated when I pushed to bower last time)

Did you try `http://illniyar.github.io/visor/sample/ui-router/#/home` ?

**Comment by vptcnt** [comment]
In fact I just noticed that I used the version 1.2.28 of angularjs. 
Could be the problem ?

**Comment by Illniyar** [comment]
with visor 0.0.4 it might. try using visor 0.0.3 or angular 1.3.x .

**Comment by vptcnt** [comment]
i changed my angular version to 1.3.8 - and visor 0.0.4 (i guess) and still the same problem...

Did you change the version in the header comment to 0.0.4 ? I couldn't find it.. still 0.0.3 I think

**Comment by Illniyar** [comment]
I didn't update the header comment, so even 0.0.4 appears like 0.0.4, look at the bower.json or package.json.

can you send/post your code, or a simulation of it, that I can check it out myself?
doea `http://illniyar.github.io/visor/sample/ui-router/#/home` work for you?

**Comment by DatenMetzgerX** [comment]
I have the same issue using ui-router. 
You can even reproduce the issue using your demo http://illniyar.github.io/visor/sample/ui-router/#/home

Click on Private, Login... now visor returns you to Home instead of "Private".

**Comment by DatenMetzgerX** [comment]
Do you have any idea what the issue might be? I could try to investigate the issue, but I'm new to visor and ui-router, so it's quite hard to figure out where the issue might be...

**Comment by Illniyar** [comment]
I think I've fixed this. please download v0.0.6 and give a try.
